### PR TITLE
Create a new combined project for iOS, Mac, and Android (SpriteBuilder #888)

### PR DESCRIPTION
**Pull request by collinjackson**

### CODE REVIEW

**Comment by slembcke** [comment]
```
fatal: reference is not a tree: 9a47cb32db67dd2c071aec70af4137a2289c2f92
fatal: reference is not a tree: eb266ee4a8fabb391019bb9b0185c63265cd8b3b
Unable to checkout '9a47cb32db67dd2c071aec70af4137a2289c2f92' in submodule path 'external/ObjectAL'
Unable to checkout 'eb266ee4a8fabb391019bb9b0185c63265cd8b3b' in submodule path 'external/SSZipArchive'
```

Did somebody forget to push the updated submodules? Doesn't build without them.

**Comment by collinjackson** [comment]
Here are the pull requests. Do you want me to merge them?

https://github.com/spritebuilder/ssziparchive/pull/3
https://github.com/spritebuilder/ObjectAL-for-Cocos2D/pull/2

**Comment by slembcke** [comment]
Ah, recursive pull request. ;) Will take a look.

**Comment by collinjackson** [comment]
You may want to check out https://github.com/spritebuilder/SpriteBuilder/pull/908 while you're at it

**Comment by slembcke** [comment]
Got stuck in a loop of "One more thing to fix" for a little too long. I merged the SSZip changes, but I don't have write access to the ObjectAL repository. So instead I merged the changes into a temporary branch until the ObjectAL changes can get merged.

This pull request will be replaced by the following:
https://github.com/cocos2d/cocos2d-swift/pull/1021

**Comment by collinjackson** [comment]
I merged the ObjectAL changes and gave you access

**Pull request closed without merging**
