### PR TITLE
Properly delete MSAA framebuffer

### PR DESCRIPTION
**Pull request by jonahb**

### CODE REVIEW

**Comment by slembcke** [comment]
Ooh. Good catch. That has probably been broken since... forever.

**Comment by jonahb** [comment]
@slembcke, something seems to have gotten messed up. I closed this pull request thinking I had submitted it to the wrong branch, and now the commit doesn't seem to have been merged. Oddly, GitHub is linking to the wrong commit above (8d2be43) and saying that I merged it.

Sorry for the hassle. Should I submit another pull request?

**Comment by slembcke** [comment]
O_o Did we break GitHub again?

I was just going to merge it by hand, but the commit seems to have disappeared out of your fork.

**Comment by jonahb** [comment]
I foolishly deleted that commit after closing this pull request. Looks like that confused GitHub.

The commit referenced in the other pull request is still there. Or, if you want this in v3.0, you can merge jonahb/cocos2d-iphone@afb336c33f. Thanks.

**Pull request merged**
