### PR TITLE
Update cocos2d/CCParticleSystem.m

### PR DESCRIPTION
**Pull request by yang3wei**
I found there'are some visual differences between retina and low resolution mode when i use a same .plist generated by ParticleDesigner.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Could you attach a test case ? Thanks.

**Comment by yang3wei** [comment]
I have sent you an email with attach project.

**Comment by ricardoquesada** [comment]
Thank you. To my gmail account ? I have not received it yet. I guess I will receive it in a few minutes.

**Comment by yang3wei** [comment]
Oh...I'm sorry about that I have sent it to 'cocos2d-iphone@noreply.github.com'，I thought it's your email address.
I'll sent it again.

**Comment by araker** [comment]
Fixed in 1.1. 

https://github.com/cocos2d/cocos2d-iphone/commit/9879ff71244fd357c2233badd043ee5dc01478ff

added you to authors in another commit.

**Comment by ricardoquesada** [comment]
As discussed with @yang3wei by email, this issue is not present on v2.0.

**Pull request closed without merging**
