### PR TITLE
Issue 1302, TMX flipped tile loading sometimes fails.

### PR DESCRIPTION
**Pull request by slycrel**
Fixed a problem with multiple layers and multiple tile sets that could cause TMX maps to not load if rotation is used.
Fixed a possible problem with tile bounds checking.

Issue 1302:
http://code.google.com/p/cocos2d-iphone/issues/detail?id=1302

### CODE REVIEW

**Comment by slycrel** [comment]
Not quite sure how to do multiple commits in one pull request....  The change to tileMapTest.m is unnecessary.  I changed that in my branch but not sure how to also add that to this pull.  Likely not a big deal either way.

**Comment by ricardoquesada** [comment]
@slycrel 
I have some issues trying to understand the patch. If possible, could you send me the "diff" ? Or, if possible, create a new pull request with only the modified files ?
If you need help with it, please, let me know. thanks.

**Comment by ricardoquesada** [comment]
Please, disregard my previous comment.

**Comment by slycrel** [comment]
Uh, okay.  Let me know if you need any additional clarification.  =)

**Comment by ricardoquesada** [comment]
Thanks. merged in v2.0

**Pull request closed without merging**
