### PR TITLE
Cocoapods

### PR DESCRIPTION
**Pull request by dylan**
Hello everyone. I put together a podspec for Cocos2d-iPhone 3.0. So far I've been able to run the sample project by starting with a template, removing the libs from the project, removing the objective chimpunk target and a making a podfile resembling this: https://gist.github.com/dylan/9797584 and running `pod install` .

Hopefully this can act as a starting point for making cocos2d/chipmunk Cocoapods compatible.

Please try it out! :smile:

### CODE REVIEW

**Comment by dylan** [comment]
Further notes:
- Need to update your app target to $(inherited) for the HEADER_SEARCH_PATHS so it inherits it from the workspace generated by cocoapods.
- I can only get it to build by setting "Build Active Architecture Only" to yes. Working on figuring out how to be able to link libPod.a for all the architectures (I may be misunderstanding something)...

**Comment by dylan** [comment]
Was this auto closed by the merge or should I look at the results of the merge and see if podspec works with the new changes?

**Comment by slembcke** [comment]
Oh my. O_o That was unexpected. We cleaned up the repository this afternoon. I guess it auto-closed all outstanding pull requests? How annoying. :(

**Comment by dylan** [comment]
It's ok, I like the cleaner branches lol...

**Comment by dylan** [comment]
I'll make sure the podspec is still ok, and make another PR.

**Pull request closed without merging**
