### PR TITLE
Clipping node

### PR DESCRIPTION
**Pull request by pierredavidbelanger**
Here is a new type of node: CCClippingNode.

This node can be used to restrict the drawing of some content (its childs) inside a stencil (an other node and its childs), also the clipping node can be used in inverted mode to restrict the drawing to the outside of the stencil instead of inside.

This node uses 
- the graphic card stencil buffer to achieve fast clipping.,
- and can optionally treat pixel bellow an alpha threshold as an absence of pixel, using the graphic card alpha test on OSX or shaders on iOS, thus allowing one to use as a stencil an image with alpha.

This branch contains:
- the code to enable the stencil buffer on iOS OES framebuffer
- a new node (CCClippingNode)
- a set of tests and demos + a new target for those tests

Everything works on iOS and OS X, using optimizations on OS X where possible.

Do not hesitate to let me know what you think.

I will stop working on this branch for now unless you need me to commit something else.

Thank you, and I hope you and the community will find this little addition as useful as I am.

### CODE REVIEW

**Comment by Panajev** [comment]
Awesome work!

[web [iPhone msg]]

**Comment by ricardoquesada** [comment]
@pierredavidbelanger 
Thanks! Merged.
2 tests are not working as expected on Mac:
- Hole Demo
- Nested Test

Any idea ? Thanks.

**Comment by pierredavidbelanger** [comment]
I will have a look at this.

Maybe its only an OSX RetinaDisplay (-hd etc..) related problem?
As I do not have access to such a machine to be able to properly test.

**Comment by ricardoquesada** [comment]
thanks.
I tested on a Non-Retina Display Mac.
Environment:
- OS X 10.7.4
- Xcode 4.5
- cocos2d "head" from develop-v2 branch.

**Comment by pierredavidbelanger** [comment]
What those two tests have in common is that the clipping nodes are nested.
Also, when run on OS X, the clipping node will use an optimisation (GL_ALPHA_TEST) instead of a slow shader hack like on iOS (this hack is due to the fact that GL_ALPHA_TEST do not exists in OpenGL ES).

I guess your problem, in the Hole Demo for example, is that you see square holes instead of small round holes? Probably because the hole_stencil.png is drawn with its invisible pixels, due the the glAlphaFunc not being properly applied on the nested stencil.

I really want to fix this, but I have a hard time figuring out how to reproduce this problem. And since it is probably a runtime issue, compiling using BaseSDK=10.7 will not help here.

May be we will need to use the OS X GL_ALPHA_TEST optimisation only when we found at runtime that the host is  at least OS X 10.8, and if not, we will fallback using shader like on iOS.

Can you describe a little what is the problem you found in the tests (what is not working as expected)?

Also can you paste here the configuration values cocos2d prints to the console (here is mine):

2012-10-22 18:40:44.385 ClippingNodeTest[6919:303] cocos2d: OS version: 10.8.2 (0x0a080200)
2012-10-22 18:40:44.385 ClippingNodeTest[6919:303] cocos2d: GL_VENDOR:   NVIDIA Corporation
2012-10-22 18:40:44.386 ClippingNodeTest[6919:303] cocos2d: GL_RENDERER: NVIDIA GeForce 9400M OpenGL Engine
2012-10-22 18:40:44.386 ClippingNodeTest[6919:303] cocos2d: GL_VERSION:  2.1 NVIDIA-8.0.61
2012-10-22 18:40:44.388 ClippingNodeTest[6919:303] cocos2d: GL_MAX_TEXTURE_SIZE: 8192
2012-10-22 18:40:44.388 ClippingNodeTest[6919:303] cocos2d: GL_MAX_TEXTURE_UNITS: 16
2012-10-22 18:40:44.389 ClippingNodeTest[6919:303] cocos2d: GL_MAX_SAMPLES: 8
2012-10-22 18:40:44.389 ClippingNodeTest[6919:303] cocos2d: GL supports PVRTC: NO
2012-10-22 18:40:44.389 ClippingNodeTest[6919:303] cocos2d: GL supports BGRA8888 textures: YES
2012-10-22 18:40:44.390 ClippingNodeTest[6919:303] cocos2d: GL supports NPOT textures: YES
2012-10-22 18:40:44.447 ClippingNodeTest[6919:303] cocos2d: GL supports discard_framebuffer: NO
2012-10-22 18:40:44.448 ClippingNodeTest[6919:303] cocos2d: GL supports shareable VAO: YES

Thank you for you time.
I will fix this :)

**Comment by pierredavidbelanger** [comment]
Hum, I think I have found something:
if you compile with the DEBUG symbol, you will probably find a bunch of "OpenGL error 0x0503", it means GL_STACK_OVERFLOW ... 

Indeed, I use a couple of glPushAttrib() when on OS X. My code is eating too much of this precious fast memory I guess :)

My graphic card probably have more stack size than yours (yet my MBP is only a mid-2009!).

The fact that glPushAttrib do not actually save the sate (so nor glPopAttrib is able to restore it) can explain why one layer of clipping node works ok, but nested clipping nodes do not render correctly.

I will try to replace every glPushAttrib/glPopAttrib in CCClippingNode with manual save/restore of the gl state I use (stencil test/alpha test/color buffer). So the code will not rely on the graphic card stack size to work properly, at the expense of a little speed.

I will create a new branch for this fix based on the develop-v2 head and notify you in this thread when its ready.

**Comment by pierredavidbelanger** [comment]
Here is the branch that I hope (I was not able to see the bug myself) will fix the problem you had with the tests: https://github.com/pierredavidbelanger/cocos2d-iphone/tree/clipping-node-alpha-test-fix

Thank you!

**Comment by ricardoquesada** [comment]
Thanks for the new patch. Unfortunately it didn't work :-(
This is the output from the console

```
2012-10-22 23:10:45.162 ClippingNodeTest[68551:403] CCGLView loaded
2012-10-22 23:10:45.232 ClippingNodeTest[68551:403] cocos2d: cocos2d v2.1-beta2
2012-10-22 23:10:45.232 ClippingNodeTest[68551:403] cocos2d: Using Director Type:CCDirectorDisplayLink
2012-10-22 23:10:45.236 ClippingNodeTest[68551:403] cocos2d: CCFileUtils: file not found: fps_images-mac.png
2012-10-22 23:10:45.239 ClippingNodeTest[68551:403] cocos2d: OS version: 10.7.4 (0x0a070400)
2012-10-22 23:10:45.241 ClippingNodeTest[68551:403] cocos2d: GL_VENDOR:   ATI Technologies Inc.
2012-10-22 23:10:45.242 ClippingNodeTest[68551:403] cocos2d: GL_RENDERER: AMD Radeon HD 6750M OpenGL Engine
2012-10-22 23:10:45.242 ClippingNodeTest[68551:403] cocos2d: GL_VERSION:  2.1 ATI-7.18.18
2012-10-22 23:10:45.244 ClippingNodeTest[68551:403] cocos2d: GL_MAX_TEXTURE_SIZE: 16384
2012-10-22 23:10:45.244 ClippingNodeTest[68551:403] cocos2d: GL_MAX_TEXTURE_UNITS: 16
2012-10-22 23:10:45.245 ClippingNodeTest[68551:403] cocos2d: GL_MAX_SAMPLES: 8
2012-10-22 23:10:45.245 ClippingNodeTest[68551:403] cocos2d: GL supports PVRTC: NO
2012-10-22 23:10:45.246 ClippingNodeTest[68551:403] cocos2d: GL supports BGRA8888 textures: YES
2012-10-22 23:10:45.246 ClippingNodeTest[68551:403] cocos2d: GL supports NPOT textures: YES
2012-10-22 23:10:45.247 ClippingNodeTest[68551:403] cocos2d: GL supports discard_framebuffer: NO
2012-10-22 23:10:45.247 ClippingNodeTest[68551:403] cocos2d: GL supports shareable VAO: YES
```

And here are the screenshots from the 2 tests:
[hole test](https://lh3.googleusercontent.com/-kl89tAzveIA/UIY1WcpbIrI/AAAAAAAAqGo/cEOvAY41QNQ/s800/Screen%2520Shot%25202012-10-22%2520at%252011.10.31%2520PM.png)
[nested](https://lh3.googleusercontent.com/-4viCxfUurCU/UIY1XQW7wPI/AAAAAAAAqGw/on_Ec_SRy7M/s800/Screen%2520Shot%25202012-10-22%2520at%252011.10.39%2520PM.png)

But I also merged this new patch in cocos2d. Thanks.

**Comment by ricardoquesada** [comment]
But I tested it on 10.8.0 and it worked OK.

```
2012-10-23 11:30:16.391 ClippingNodeTest[56552:303] cocos2d: cocos2d v2.1-beta2
2012-10-23 11:30:16.391 ClippingNodeTest[56552:303] cocos2d: Using Director Type:CCDirectorDisplayLink
2012-10-23 11:30:16.435 ClippingNodeTest[56552:303] cocos2d: CCFileUtils: file not found: fps_images-mac.png
2012-10-23 11:30:16.436 ClippingNodeTest[56552:303] cocos2d: OS version: 10.8.0 (0x0a080000)
2012-10-23 11:30:16.436 ClippingNodeTest[56552:303] cocos2d: GL_VENDOR:   ATI Technologies Inc.
2012-10-23 11:30:16.436 ClippingNodeTest[56552:303] cocos2d: GL_RENDERER: AMD Radeon HD 6750M OpenGL Engine
2012-10-23 11:30:16.437 ClippingNodeTest[56552:303] cocos2d: GL_VERSION:  2.1 ATI-1.0.25
2012-10-23 11:30:16.437 ClippingNodeTest[56552:303] cocos2d: GL_MAX_TEXTURE_SIZE: 16384
2012-10-23 11:30:16.438 ClippingNodeTest[56552:303] cocos2d: GL_MAX_TEXTURE_UNITS: 16
2012-10-23 11:30:16.438 ClippingNodeTest[56552:303] cocos2d: GL_MAX_SAMPLES: 8
2012-10-23 11:30:16.438 ClippingNodeTest[56552:303] cocos2d: GL supports PVRTC: NO
2012-10-23 11:30:16.438 ClippingNodeTest[56552:303] cocos2d: GL supports BGRA8888 textures: YES
2012-10-23 11:30:16.439 ClippingNodeTest[56552:303] cocos2d: GL supports NPOT textures: YES
2012-10-23 11:30:16.439 ClippingNodeTest[56552:303] cocos2d: GL supports discard_framebuffer: NO
2012-10-23 11:30:16.439 ClippingNodeTest[56552:303] cocos2d: GL supports shareable VAO: YES
2012-10-23 11:30:16.439 ClippingNodeTest[56552:303] cocos2d: Director's thread: DisplayLink thread
```

**Comment by pierredavidbelanger** [comment]
May be its related to how 10.8 vs 10.7 handle floating point calculation for the depth test (I really do not know where to look :)).

Anyways, here is an other branch containing various fixes, including (among other things) bypassing the depth test while drawing the stencil node:
https://github.com/pierredavidbelanger/cocos2d-iphone/tree/clipping-node-various-fixes

If this is not working, I will take a little break as I have the feeling this little back-and-forth is consuming too much of your time. And I will find a way to test/fix the problem myself.

Thank you for you patience :)

**Comment by ricardoquesada** [comment]
@pierredavidbelanger 
Unfortunately it didn't work either on 10.7.4

Anyway, I don't have any problem in testing more patches for this bug. It is really easy for me to test them with pull requests.
Thanks.

**Comment by pierredavidbelanger** [comment]
I am back :)

So I installed a fresh copy of 10.7.4 on an spare partition. I was unable to reproduce the problem. It become clear it is a GL_RENDERER issue.

But while playing with the code a little, I was able to see exactly what you see (in your screenshots): all tests are ok expect for the two that use nested clipping node. In the HoleDemo nothing is drawn, and in the NestedTest all grossini except the first one are not drawn.

I was able to reproduce this by messing with the depth buffer: I forced it to always fail on all the nested clipping node except for the first level.

I guess that, on some GL_RENDERER versions, even if we draw invisible things, even only on the stencil buffer, the depth buffer is updated.

So the fix (i really hope it fixes something :)) is to disable update to the depth buffer while drawing the stencil node.

This is committed to my https://github.com/pierredavidbelanger/cocos2d-iphone/tree/clipping-node-various-fixes branch, along with -hd version of the hole sprite used in the ClippingNodeTest target.

I know it is a little late to ask you this, but please tell me (or point me to the right documentation url that explain) what should be the right workflow to send you patches for cocos2d.

Should I create a github pull request each time?

For example here in this thread, all my commits are related to one topic, should have I created many pull request anyway?

In any case, thank you again for you patience. I will fix this bug :)

**Comment by Panajev** [comment]
Hey and thank you for your great work Pierre!

I would too need to ask Riq a bit of a submodules refresher in order to
keep new branches in cocos2d forks synched with the upstream repo
(considering what the submodules are, basically none of the changes I
worked on were on any submodule, but I would not want to do operations in
the wrong sequence), but I think the following could be a sane way to do
this.

In terms of patches all related to the same bit of functionality, like in
this case.
The way GitHub handles pull requests is quite nice as you do not need to do
anything to update your pull requests. You only need to commit your changes
to your branch, the one you have used to make the pull request to begin
with, and then push those changes to your repo on Github (where your fork
of Cocos2D is).
You can keep on doing this, commit + push, after you have made the first
pull request since you are still working on the same component you wanted
to add in the first place so to speak.

In terms of separate features or fixes to different portions of Cocos2D
functionality, I would do a pull request for each macro-item and then
handle each one like you have done for this current item.

**Comment by pierredavidbelanger** [comment]
@Panajev 

Thank you for you explanation. It is a shame I did not knew about this GitHub same-branche-pushes-update-original-pull-request feature :) It really make sense.

Knowing that, I will now merge all my clipping-node-\* branches on the clipping-node branch. All my next commits will be pushed to this branch.

**Comment by ricardoquesada** [comment]
@pierredavidbelanger 
Thanks for the new patch (merged into develop-v2 branch). But unfortunately it didn't fix the bug on the Mac :-(

I don't know where it is failing, but if you could send me a "debug" version of the patch with lots of error-checking-code, I will run it and post the log here.

Thanks!

**Comment by ricardoquesada** [comment]
@Panajev @pierredavidbelanger 
Ah... and the best way to send me a patch for a submodule, is to clone the submodule repository, and do exactly the same for that repo.
Example: If you want to send a patch for JS bindings submodule:
- clone the JS Bindings repo: ( https://github.com/ricardoquesada/jsbindings )
- and send a pull request for that repo

To see which are the repos used, you can run this command:
`
$ git submodule foreach git remote -v
`

**Comment by pierredavidbelanger** [comment]
@ricardoquesada 

Hi!

I took some time today to create new tests to try to pin point our problem with the ClippingNode on OS X.

I pushed them in my clipping-node branch.

If you compile the target ClippingNodeTest with COCOS2D_DEBUG=2 you will see 5 more tests.

They are not meant to be pretty nor high in fps :) But they contains enough infos (I hope) to help me understand better what happen.

Here on 
- Simulator (iPad and iPhone, iOS 5.0, 5.1 and 6.0), 
- iPhone 4, iOS 6
- iPad 2, iOS 6
- mid-2009 MBP, OS X 10.8 and 10.7

the first three tests looks like this:
https://www.dropbox.com/s/qqkeq8l4l99qt3n/wo_alpha_test.png

the last two tests looks like this:
https://www.dropbox.com/s/xq1ljwfv42wl9k4/w_alpha_test.png

If you can post some screen shots where the tests are not conform to my screen shots it will be really appreciated.

Thank you!

**Comment by ricardoquesada** [comment]
@pierredavidbelanger 
Here are the screenshots. Thanks!

test1

test2

test3

test4

test5

**Comment by pierredavidbelanger** [comment]
Wow, this is sad!

Ok, so, it looks like it is not a depth test nor an alpha test related problem.

I pushed one more commit that contains one more test (number 6).

This new test try to avoid using glClear before drawing each stencil plane (because I guess it somehow do not take the glStencilMask into account, thus always clearing the entire buffer instead for only the plane bit it should).

Also this test display two labels at the top (only on OSX because it uses glReadPixels).

Here the values are 00=00 and 0a=0a, it means that glClear take into account the glStencilMask.

But if you see 00=00 and 0a=aa, it means that glClear do NOT take into account the glStencilMask.

Again, thank you for your patience.

**Comment by ricardoquesada** [comment]
@pierredavidbelanger 
Thanks. Here is the screenshot:
test6

**Comment by pierredavidbelanger** [comment]
Hum, this is at last graphically the expected output!

But what bugs me, is that I would have expected from your specific gl renderer to show 0a=aa at the top (thus explaining why the manual clear is working).

Anyways, if you dont mind, (maybe I am being a little picky but) I do not like manually clearing the stencil buffer, it smells like a dirty hack. So this will be plan B.

I am starting to think that the fix will be to only put a little glFlush after the glClear for each nested stencil plane 
(still I do not know whats more evil: random glFlush or manual clearing by drawing a fullscreen invisible rectangle :confused: ).

So either you put a glFlush(); at line 767 of ClippingNodeTest.m or you pull my last single line commit.

This will be effective for the RawStencilTest 1 to 5.

**Comment by ricardoquesada** [comment]
Thanks. 
I tried your latest pull request ( `glFlush()` ), but Test 1-5 looks the same :-(

**Comment by Panajev** [comment]
It might be a hack, but I would think that flushing the pipeline to be worse than that, especially performance wise unless there is no other way.

[web [iPhone msg]]

**Comment by pierredavidbelanger** [comment]
@Panajev I agree. glFlush can sometime make the application wait for the command buffer to be empty before returning, this can be dramatic to the fps. And the commands to draw a single rectangle will surely be queued to the command buffer by the hardware. So, its smelly, but indeed its faster :)

@ricardoquesada So the plan B is the solution (manual clear of the stencil buffer). It will work on all platforms cocos2d supports.

I will take some time to apply this solution into CCClippingNode.

Thank you!

**Comment by pierredavidbelanger** [comment]
The fix is pushed in my branch.

Thank you!

**Comment by ricardoquesada** [comment]
Thanks!
The hole and nested tests are working OK now.

**Pull request merged**
