### PR TITLE
CCArray additions

### PR DESCRIPTION
**Pull request by araker**
ccCArray, added ccArrayShrink to reduce the size of the array to the number of items (instead of the max number of items)

CCArray, added reduceMemoryFootprint which calls ccArrayShrink
and added a reverse method.

### CODE REVIEW

**Comment by araker** [comment]
ActionInterval additions 
- added 
  pause 
  resume
- Limitations, don't pause/resume a nested ActionInterval, pause/resume the parent action interval instead.

CCSequence 
For testing purposes I've named the new CCSequence CCSequenceNew, so the two implementations can be tested alongside.

The new sequence has a array implementation instead of nested items
-added  
    reset  
    resetWithArray

ActionsTest
Two new tests
- pause/resume
- stop/reset

@Riq, the first commit are the changes to CCArray, the other two are the changes to ActionInterval and CCSequence.

**Comment by ricardoquesada** [comment]
Thanks. Patch merged sometime ago.

**Comment by ricardoquesada** [comment]
Actually the CCArray patch was merged, the Action patches were not merged yet. Reopening pull request.

**Comment by araker** [comment]
I'm closing this pull request, since I'm still working on a improved action system. The code in the request is outdated.

**Pull request closed without merging**
