### PR TITLE
Adds optional completion handler for actions

### PR DESCRIPTION
**Pull request by chrene**
This is just one thing I really have missed in the other versions. The ability to get notified when your actions are completed, using blocks.

I tested it with actions running simultaneously and the completion handlers were called as wanted.

### CODE REVIEW

**Comment by Panajev** [comment]
Neat :)

[web [iPhone msg]]

**Comment by dominik-hadl** [comment]
Very nice. Even though it was possible to chain a CCCallBlock in a CCSequence to achieve the same thing, this approach is much simpler.

**Comment by Birkemose** [comment]
We are releasing 3.0 tomorrow, so everything is locked down for now. Looks like a really great feature, so someone will review it asap.

**Comment by chrene** [comment]
Yeah saw the RC update on the forums, so that's what I thought too :)

**Comment by cocojoe** [comment]
Can someone please review this.

**Comment by Birkemose** [comment]
As far as I can see, the code looks solid and works.
When merged, we should definitely add some more action testing.

**Pull request closed without merging**
