### PR TITLE
Modify CCLabelBMFont for multiline alignment

### PR DESCRIPTION
**Pull request by pingpongboss**
Left, Center, and Right alignments.
Auto word wrap based on given width.

Based on https://github.com/pingpongboss/CCLabelBMFontMultiline

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Hi PingPong,

Many thanks for the patch. I have just tested, and I like the new functionality. 
But it has one major problem with the performance. Every time the label is updated, all the characters all deleted and recreated. This is too expensive for labels that might be updated every frame.

Do you think it would be possible to fix that issue ? Thanks again.

**Comment by pingpongboss** [comment]
Hi Ricardo,

Ah, I haven't thought about the performance ramifications. The reason why I remove all the characters is that if I don't, some funky stuff happens with whitespaces and I either can't auto-line-break correctly (step 1), or I can't count the number of characters correctly for alignment (step 2). It has something to do with createFontChars reusing the old children in some bad way.

I will give it a try to make it work, but if it's possible maybe someone could take a look at createFontChars to see what's going wrong.

**Comment by ricardoquesada** [comment]
Hi PingPong,

I developed "createFontChars" so I can help you with that. Could you describe a bit further the issue and how to reproduce it ? 
Thanks.

**Comment by pingpongboss** [comment]
Sure, let me play around with disabling removeAllChildren and observe the side-effects again.

**Comment by ricardoquesada** [comment]
Ok. Thanks.

On 11 November 2011 21:26, Mark Wei
reply@reply.github.com
wrote:

**Comment by pingpongboss** [comment]
Hey Ricardo,

Sow I thought it was impossible for me but I think I've done it. Can you check out the latest changes and see if they work for you.

The main problem I was having was that I was under the assumption that doing a `for(CCSprite *child in children_)` would go through the children in order. But instead, I had to go by the tag to go in order. I also had to take care of the cases where a child would be missing for a specific tag, for example: `[children_ count]` returns 3, but only children with tags 1, 2, and 4 exist. Lastly I had to skip over children who were not `visible`.

I'm not sure where these side-effects came from, but I'd guess it comes from `createFontChars`'s optimizations when you give the label a new, similar string to render.

Thanks,

**Comment by pingpongboss** [comment]
ah, btw you can call me Mark

**Comment by ricardoquesada** [comment]
Thanks Mark,

I will test it today.

**Comment by pingpongboss** [comment]
Cool, let me know if there are any problems

**Comment by ricardoquesada** [comment]
Thanks Mark.
Patch merged in gles20 branch.
https://github.com/cocos2d/cocos2d-iphone/commits/gles20

**Pull request closed without merging**
