### PR TITLE
Added support for vertical alignment in labels

### PR DESCRIPTION
**Pull request by kstenerud**
You can now align labels vertically as well as horizontally.

Works in iOS and Mac.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Thanks. Will be merged in 1.1 and  2.0

**Comment by horatio-sans-serif** [comment]
This isn't in 1.1 from what I can tell. What's the plan?

https://github.com/cocos2d/cocos2d-iphone/blob/release-1.1-beta2b/cocos2d/CCLabelTTF.h

**Comment by ricardoquesada** [comment]
@fictorial 
Support for vertical alignment was added in v2.0

**Comment by horatio-sans-serif** [comment]
Thanks, I just sized the font with UIFont/ZFont and laid it out manually for now (1.1).

This isn't the place to ask this I'm sure but when is 2.0 expected to be "done"?

**Comment by ricardoquesada** [comment]
@fictorial pretty soon :) Right now it is pretty stable. Feel free to continue this discussion on the cocos2d forum.

**Comment by digitalhoax** [comment]
Will this work in pre 2.0 as well (e.g. 1.0.1 and 1.1)? To be more precise, will this work in the latest stable 1 version, which is 1.0.1 as of now?

**Comment by araker** [comment]
I've implemented it in 1.1. I'm preparing a RC0 release, which will be ready within 2 weeks. 

https://github.com/cocos2d/cocos2d-iphone/commit/d2b2a33b63a1adae78c27493649c3517264707b1

Closing this one.

**Pull request closed without merging**
