### PR TITLE
CCParticleSystemPoint -> CCParticleSystemQuad

### PR DESCRIPTION
**Pull request by sirsean**
CCParticleSystemPoint has been removed from this branch, and CCParticleSystemQuad works on armv6. So by removing the reference to CCParticleSystemPoint, cocos2d will successfully compile for armv6 and can be used on older iPhones.

### CODE REVIEW

**Comment by araker** [comment]
@sirsean, I don't understand your pull request. Did you intend this for the 2.0 branch?

**Comment by sirsean** [comment]
I did, that's where I attempted to make it. Did it end up going to the
wrong branch?

On Thu, Mar 22, 2012 at 6:51 PM, araker <
reply@reply.github.com

**Comment by araker** [comment]
Yes, the develop branch is for 1.1. You'll need to send your pull request to the gles20 branch. I'll close this one.

**Comment by sirsean** [comment]
Thank you, sorry for screwing that up.

On Fri, Mar 23, 2012 at 10:25 AM, araker <
reply@reply.github.com

**Pull request closed without merging**
