### PR TITLE
CCEffectLighting - Fixes for SpriteBuilder editing

### PR DESCRIPTION
**Pull request by thayerandrews**
- Limit publicly visible shininess range to [0..1]. It used to be [0..inf] but this was a) confusing and b) hard to edit in SpriteBuilder. Internally the normalized values are mapped to a shader friendly range.
- Fix handling of the specular of directional lights.

### CODE REVIEW

**Comment by slembcke** [comment]
This conflicts with https://github.com/cocos2d/cocos2d-swift/pull/1099 and I'm not quite sure how to resolve the merge.

**Comment by thayerandrews** [comment]
Yup. I'm resolving it right now. I should be able to push an update in the next couple of minutes.

**Comment by slembcke** [comment]
Thanks.

**Comment by thayerandrews** [comment]
You're welcome. Thank you for reviewing and merging these. I know the CCEffects refactor was pretty wide-ranging.

**Pull request merged**
