### PR TITLE
Changed a  number of 32-bit float literal constants to doubles.

### PR DESCRIPTION
**Pull request by pkclsoft**
Changed a  number of 32-bit float literal constants to doubles by removing the 'f' suffix.

### CODE REVIEW

**Comment by richardgroves** [comment]
Nice work - improves it for the modern platforms.

I'm beginning to bore myself on this - but  CCActionEaseRate and CCActionEaseElastic should probably have their 'rate' and 'period' values as CGFloat's.

Line 39 of CCActionEase still leaves the (float) cast in for M_PI_X_2

**Comment by pkclsoft** [comment]
Darn.  Getting bored too.

**Comment by pkclsoft** [comment]
Have updated with your suggestions.

**Comment by pkclsoft** [comment]
Added a new commit to fix an issue in CCScrollView on iOS 9.

**Pull request merged**
