### PR TITLE
Actually attach the stencil part to the framebuffer...

### PR DESCRIPTION
**Pull request by pierredavidbelanger**
... when creating a CCGLView using GL_DEPTH24_STENCIL8_OES as depthFormat.

To be able to use GL_STENCIL_TEST into CCNode draw/visit.

I am no OpenGL expert but i think this was missing.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Thanks. What is the best way to test it ? Do you have a test case ?

**Comment by pierredavidbelanger** [comment]
Thank you for your interest!

If you want, you can wait a little before pulling those changes, I will write some tests and merge them into this branch.

**Comment by ricardoquesada** [comment]
Sure, that would be great! thanks.

**Comment by pierredavidbelanger** [comment]
I have submitted a new pull request (https://github.com/cocos2d/cocos2d-iphone/pull/252), that contais this branch + a useful (i hope) addition to cocos2d.

But if you reject my new pull request, this branch (attach-stencil-to-framebuffer) will stay on my fork for you to pull it.

**Comment by ricardoquesada** [comment]
Thanks.
Pull request #252 was merged as well.

**Pull request merged**
