### PR TITLE
Support for transitions when pushing and popping scenes.

### PR DESCRIPTION
**Pull request by Panajev**
Added support for scene pushing and popping using animated transitions.

### CODE REVIEW

**Comment by rsanchezsaez** [comment]
Does this work when popping the last scene? (Transition to black). If it does, this could be really great!

**Comment by Panajev** [comment]
Theoretically, Cocos2D transitions are used to go from one scene to another
scene. It would work well if you had an empty scene for it to transition to
and you used a transition that allowed you to fade with the appropriate
color.

Otherwise, this patch follows the same limitations for pushing scenes and
popping scenes the director previously had. I'll give this some more
thought. I was planning this feature for things like menus and other layers
you might want to pop in and out quickly but with a nice transition effect.
I am also planning to use something other than strings for selecting the
transitions... the current way is not exactly code completion friendly.

**Comment by rsanchezsaez** [comment]
Thanks for the info. Looks quite useful anyway!

**Comment by Panajev** [comment]
Thank you :).

**Pull request closed without merging**
