### PR TITLE
support for Mac OS X Retina displays

### PR DESCRIPTION
**Pull request by stuartcarnie**
Add retina support for Mac OS X. This is needed in order to merge in [SpriteBuilder #705](https://github.com/spritebuilder/SpriteBuilder/issues/705)

### CODE REVIEW

**Comment by cocojoe** [comment]
Anyone have any issues with this otherwise will merge, the Director changes are isolated to Mac Director. Always weary of `CCFileUtils` changes however shouldn't be an issue, @2x goes against our v3 Cocos2D conventions however makes sense for SB App.

**Comment by stuartcarnie** [comment]
Agree on @cocojoe's **@2x** comment. The justification for supporting **@2x** when compiling for Mac was for apps like SpriteBuilder, that are developed primarily in Xcode and an application rather than a game – both of which benefit from the @2x suffix from a tooling perspective. Sketch 3 or Affinity Designer natively use the **@2x** suffix, so it removed some friction to knock this out relatively quickly.

**Comment by cocojoe** [comment]
@slembcke Any thoughts on this? I would like to get this in for retina SB pull however throwing in @2x now seems a bit random however does make sense in an Mac App and seems unfair for @stuartcarnie to now rename files ;-)

**Comment by stuartcarnie** [comment]
Another workflow benefit of the **@2x** suffix on a retina Mac is they are shown at the same size as their **@1x** counterparts in Finder and Xcode, but in higher resolution

**Comment by slembcke** [comment]
I don't have a retina Mac to test on (iMac coming next week :D). I think it looks fine though.

There is already "-machd", which I honestly don't know if anybody uses. Using @2x on iOS actually breaks things since the image loading code still uses UIImage. Shouldn't make a difference on Mac though. We've committed to a complete overhaul of CCFileUtils for v4, so this will end up changing in the coming months.

**Pull request merged**
