### PR TITLE
Gles20

### PR DESCRIPTION
**Pull request by Panajev**
Added uniform caching mechanism. Jumpy Lens3D's redundant calls down to 15 (30 s period).

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Thanks.
How is the performance with your changes ?

**Comment by Panajev** [comment]
Well, the number of redundant calls is basically trivial now (compared to before) and performance seems improved, but in order to give you hard numbers I'd need to benchmark it accurately. What do you suggest? Thanks :)

**Comment by ricardoquesada** [comment]
I usually run the performance tests (specially the Performance Sprite
Test   cocos2d-iphone/tests/Performance ) to understand how fast/slow
are the changes.
And I compare the results with these tests:
http://www.cocos2d-iphone.org/wiki/doku.php/perf_test:2_0_0

If you can run it, great. Otherwise, I will run them before the merge.
Thanks.

On 13 February 2012 11:42, Panajev
reply@reply.github.com
wrote:

**Comment by Panajev** [comment]
I am running the tests, Sprites and Particles, and looking at them performance seems to be about the same.One area that would need optimization (NEON) would be the function that checks (using kazmath's built in method) the incoming matrix that the user wants to update: the faster this is done, the better.

Right now, most of the redundant state changes Cocos2D performs are 1.) updating the MVP matrix each frame and 2.) calling glViewport(). Those two account, without the current patch, for the majority of redundant uniform updates. The more uniforms are used by custom shaders the higher the chance that uniform caching helps Cocos2D out.

Still, sorry for not giving you hard numbers, but I am having a bit of  a hard time collecting them when some of them fluctuate on the screen :(.

**Comment by Panajev** [comment]
Example: D(5) with 4,000 particles stays most of the time at 8.6 FPS (from what I read) with infrequent dips below that (blips). On the results page I see ~8.

**Comment by ricardoquesada** [comment]
thanks for the info!
I will try to merge it during this week.

**Comment by Panajev** [comment]
I have added another commit with some further cleanup work (removing some cruft). I hope this is ok.

**Comment by Panajev** [comment]
Do you analyze the output of the performance tests with some tool (and if so, how do you collect the data besides looking at the current FPS counter on screen?) or just see that the number does not produce some nasty results? I find it hard to measure few percentage points of performance whether it is a positive or negative difference :).

**Comment by ricardoquesada** [comment]
For certain tests, I use the FPS counter. For other tests I use the CCProfiler class.
The FPS counter is not very reliable... The "Seconds Per Frame" is a bit more reliable, but not that much.

And usually what I do is just that: See if the numbers are not slower (or not slower than 2% ~ 3%) than the previous version.

**Comment by Panajev** [comment]
Ok, thank you for the explanation :). I agree that most of the times the FPS counter was not reliable, but taking an average FPS value then min and max FPS after running the cycling benchmark could provide more interesting data.

[web [iPhone msg]]

**Comment by ricardoquesada** [comment]
I like your idea. Probably I am going to change a little bit the API, but the idea is good.

**Comment by ricardoquesada** [comment]
thanks. added "uniform" cache here:
https://github.com/cocos2d/cocos2d-iphone/commit/38c97219bfffefd6dca996d70e91db1bfc29a72d

**Comment by Panajev** [comment]
Beautiful, I like the elegance of this implementation :), thank you for
integrating the code and improving on it!
The -updateUniformLocation method does its work more cleanly, but should
also be faster than before. Important, because this was the potential
bottleneck for such a cache.

On Mon, Feb 20, 2012 at 11:49 PM, Ricardo Quesada <
reply@reply.github.com

**Comment by ricardoquesada** [comment]
thanks.
I have not done any performance test between old_cache vs. new_cache,
but I think the new one should be little bit faster since it doesn't
use objective-c data structures...

On 20 February 2012 15:09, Panajev
reply@reply.github.com
wrote:

**Pull request closed without merging**
