### PR TITLE
Fix outline color on CCLabelTTF.

### PR DESCRIPTION
**Pull request by toreolsensan**
Without this, setting a CCLabelTTF's outlineColor property has no effect.

### CODE REVIEW

**Comment by nheagy** [comment]
Beautiful, I have been wondering what was up with that.

**Comment by vlidholt** [comment]
Has this been tested with both iOS 6 and 7? Does setting the width of the outline and shadow work correctly?

**Comment by toreolsensan** [comment]
@vlidholt This has been tested on devices running iOS 6.1.3 and 7.0.6. Shadows with different color/offset works, as does the outline width (it seems NSAttributedString doesn't explicitly set line width, like it does with the foreground color). shadowBlurRadius does work. Are there any other parameters you think should be checked?

**Comment by gimsangtae** [comment]
Thanks. great work.

**Comment by toreolsensan** [comment]
@slembcke What happened to this pull request? Suddenly it contains thousands of commits, and was apparently closed without merging my commits. Is there any point in resubmitting?

**Comment by orionnoir** [comment]
check out some of the other recent posts. turns out there might have been
some very unintentional side effects of a recent action doing something for
3.0. I haven't seen any resolution decision yet, but I read it was
unintentional.

**Comment by slembcke** [comment]
It was closed automatically as an unintentional side effect. when we tried to cleanup and rename the branches. More details here:
http://www.cocos2d-iphone.org/forums/topic/important-read-me-git-users/

**Pull request closed without merging**
