### PR TITLE
Ensure pushed scenes directly or via transition will resume with pop correctly.

### PR DESCRIPTION
**Pull request by cocojoe**
Can someone with more CCDirector experience check this please.
Fixes: #560 #608 #616

### CODE REVIEW

**Comment by Birkemose** [comment]
The problem as I see it, is, that is the scene was paused before pushing, it will be unpaused when popping.
I havent looked into the original problem though.

**Comment by cocojoe** [comment]
If there is a transition with the push it will pause the outgoing scene.  A subsequent pop will not resume it.

A straight push/pop works without transition worked fine.

**Comment by Birkemose** [comment]
Let me check up on it

**Comment by Birkemose** [comment]
We will need an extra pause variable, if we want to preserve user pause when popping a scene. For now let us merge this, and simply force pause off when the scene is popped.

**Comment by slembcke** [comment]
I agree that it's an improvement, but still not a complete fix. It seems like a pretty minor bug that somebody would pause a scene and then push it though. I guess we should merge it as is and make a separate issue?

**Comment by slembcke** [comment]
I thought this got merged. :-\ I guess I'll push the button.

**Pull request merged**
