### PR TITLE
Removed forward declarations for tFontDefHashElement and tKerningHashElement

### PR DESCRIPTION
**Pull request by Panajev**

### CODE REVIEW

**Comment by Ricardo1980** [comment]
I tested the last modification and doesn't work properly. In landscape, my sprite is not centered when first scene is loaded, but centered if I move those 2 lines to their original position.
And BTW, with that modification it seems there is no flicker.

**Comment by Panajev** [comment]
That is strange. So it's either flicker and correct centering or no flicker and wrong sprite positioning at start?
Riq? Ideas?

**Comment by Ricardo1980** [comment]
Did you see that strange behavior or would you like I create a test case?

**Comment by Panajev** [comment]
If you could create a text case I'd appreciate it a lot, thanks :). As far as the missing structs issue, yes I have.

[web [iPhone msg]]

**Comment by ricardoquesada** [comment]
Strange... I cannot reproduce this issue...
I have a test (bug350), and it is working ok.

**Comment by Ricardo1980** [comment]
I created a test case for you. 
Donwload this file.
http://www.4shared.com/zip/m-MpBbM_/TestFlickering.html
If you have problems downloading it, tell me about it.

Now you can see a flicker. If you move those 2 lines after pushScene, there is no flicker, but first sprite is not centered, and what is even more strange, if you change to another scene and come back, position is right.

Test it and tell me.
Thanks for help.

**Comment by ricardoquesada** [comment]
thanks. merged in develop-v2 branch

**Pull request closed without merging**
