### PR TITLE
CCBReader updated for new blendmode written by Spritebuilder.

### PR DESCRIPTION
**Pull request by NickyWeber**
Updated binary reader for new blend mode written by spritebuilder.

In conjunction with SB pull request: https://github.com/spritebuilder/SpriteBuilder/pull/1324

### CODE REVIEW

**Comment by slembcke** [comment]
√

**Comment by andykorth** [comment]
Maybe I'm super confused, but it looks like those blend mode changes are in a flipX and flipY block. They should be down a block?

Also, I'll be that guy: looks like the indentation inside each #if DEBUG_READER_PROPERTIES preprocessor block is wrong. _shrugs_. Maybe we can get that later all at once.

**Comment by slembcke** [comment]
Hmm. Yeah. It's a little more clear when the diff context is expanded.

**Comment by NickyWeber** [comment]
@slembcke Sorry that was my mistake, I had it set up correctly in my SB project but copy and paste was a missed target. Pushed a correction.

How should the the `#ifdefs` look like? I think that I indented the code it encapsulate with the same level as the surrounding code.

**Comment by rkachowski** [comment]
Is it possible to merge this? 

Currently the writer version is out of sync with the reader, and spritebuilder will generate files that it can't read :/

**Comment by andykorth** [comment]
Let's definitely not delay it about indentation.

**Pull request merged**
